### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by tonsV2**

### CODE REVIEW

**Comment by sobolevn** [comment]
Maybe we can try https://github.com/wemake-services/caddy-gen/blob/master/docker-gen/templates/Caddyfile.tmpl#L5 ?

**Review by sobolevn — COMMENTED** [review]
Thanks a lot!

**Comment by tonsV2** [comment]
Locally it works just fine, port 2015 returns 404. On travis it returns 400. I don't know why.

**Comment by sobolevn** [comment]
@tonsV2 maybe we can have a look at the response headers and body, not only status code? We can also enable logs on caddy's side to figure this out. It might be a bug!

**Comment by tonsV2** [comment]
Yeah, Ideally we should assert all open ports. I've added the verbose flag to the curl command but it gives little information. I've tried to enable debugging on Caddy but I can't seem to get it working. Granted I haven't put a lot of effort into it. But do you have any idea about how to do it?

**Pull request closed without merging**
